export const LIVE_STATE = ["INPLAY_1ST_HALF", "INPLAY_2ND_HALF"];

export const LIVE_STATE_NAME = {
  INPLAY_1ST_HALF: "1MT",
  INPLAY_2ND_HALF: "2MT",
  INPLAY_EXTRA_TIME: "PROL",
  INPLAY_PENALTIES: "TIRS AU BUT",
};
