services:
  backend:
    image: ${BACKEND_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    environment:
      - .env
    ports:
      - "3333:3333"
    command: >
      sh -c "
      until nc -z postgres 5432; do
        echo 'Waiting for PostgreSQL...';
        sleep 2;
      done;
      node ace migration:run --force && node bin/server.js"
    depends_on:
      - postgres
      - redis

  # frontend
  frontend:
    image: ${FRONTEND_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    environment:
      NODE_ENV: production
      SESSION_SECRET: ${SESSION_SECRET}
      BASE_URL: ${BASE_URL}
    ports:
      - "3000:3000"
    command: >
      sh -c "
      echo 'Starting Remix frontend...';
      pnpm start"
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis
    environment:
      - REDIS_PASSWORD=
    command: ["redis-server", "--requirepass", ""]
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  redis_data:
