name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main
      - refactor/frontend

env:
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/superligfr-backend:latest
  FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/superligfr-frontend:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build et push backend
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.BACKEND_IMAGE }}
          target: backend

      # Build et push frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            echo "Déploiement sur le VPS..."
            export $(grep -v '^#' ~/stacks/.env | xargs)
            cd ~/stacks
            docker stack deploy -c docker-compose.yml superligfr
